version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: plant
      POSTGRES_USER: plant
      POSTGRES_PASSWORD: plant
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plant"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "6379:6379"
  web:
    build: .
    command: bash -lc "./scripts/entrypoint-web.sh"
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  worker:
    build: .
    command: bash -lc "./scripts/entrypoint-worker.sh"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
volumes:
  static_volume:
  media_volume:
  pg_data:
